service: chatgpt-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-1
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
functions:
  slack:
    handler: handler.handler
    timeout: 30 # defaultの6秒だと定期的にtimeoutする
    events:
      - http:
          path: /
          method: post
plugins:
  - serverless-python-requirements
